### PR TITLE
MH scrpit to produce amm file compatible with situated-annotated

### PR DESCRIPTION
**Pull request by humsha**
The script "intake/create-glozz-aam-nonling.py" is added. 
It produces nonling compatible .aam file. 
This script is a copy of the existing "create-glozz-aam.py" with a change at line 206.

### CODE REVIEW

**Comment by moreymat** [comment]
@humsha Is this a real pull request?

**Comment by humsha** [comment]
Yes! I just redo the old pull request using a new branch.

**Comment by moreymat** [comment]
Have you considered expanding the _existing_ script, instead of adding a 99.5% identical copy?

**Comment by humsha** [comment]
I did not considered that. It is a good idea thanks :D I'll update the existing script with a command line option to have a situated compatible .aam file.

**Pull request closed without merging**
